run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - typecheck

linters-settings:
  govet:
    disable:
      - shadow
      - fieldalignment
  errcheck:
    exclude-functions:
      - (*database/sql.Tx).Rollback
      - (*github.com/jackc/pgx/v5.Tx).Rollback
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write
      - encoding/json.NewEncoder.Encode
      - encoding/json.NewDecoder.Decode
      - encoding/json.Unmarshal
      - os.WriteFile
      - io.Copy
      - rand.Read

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
        - govet
    - path: cmd/
      linters:
        - errcheck
    - path: scripts/
      linters:
        - errcheck
        - unused
    - path: internal/
      linters:
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  sort-results: true
