run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    disable:
      - shadow
      - fieldalignment

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - staticcheck
    - path: cmd/
      linters:
        - staticcheck
    - path: scripts/
      linters:
        - staticcheck

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  sort-results: true
